name:                motopaint
version:             0.1.0.0
github:              "p4l1ly/motopaint"
license:             BSD3
author:              "Pavol Vargovčík"
maintainer:          "pavol.vargovcik@gmail.com"
copyright:           "2020 Pavol Vargovčík"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/p4l1ly/motopaint#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- random
- diagrams
- diagrams-lib
- diagrams-svg

library:
  source-dirs: src

executables:
  motopaint-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - motopaint

tests:
  motopaint-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - motopaint
